/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import BO.Cliente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Renan 2016
 */
public class CadCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadTeste
     */
    public CadCliente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnome = new javax.swing.JTextField();
        lbdtnascimento = new javax.swing.JLabel();
        txtdtnascimento = new javax.swing.JFormattedTextField(pegarFormatterDate());
        lbtelefone = new javax.swing.JLabel();
        txttelefone = new javax.swing.JTextField();
        lbendereco = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        lbbairro = new javax.swing.JLabel();
        txtbairro = new javax.swing.JTextField();
        lbcidade = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        lbrg = new javax.swing.JLabel();
        lbcliente = new javax.swing.JLabel();
        txtrg = new javax.swing.JTextField();
        lbpesquisa = new javax.swing.JLabel();
        lbcpf = new javax.swing.JLabel();
        rbnome = new javax.swing.JRadioButton();
        txtcpf = new javax.swing.JTextField();
        rbcpf = new javax.swing.JRadioButton();
        lbcnpj = new javax.swing.JLabel();
        txtpesquisa = new javax.swing.JTextField();
        txtcnpj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcliente = new javax.swing.JTable();
        btsalvar = new javax.swing.JButton();
        btalterar = new javax.swing.JButton();
        lbid = new javax.swing.JLabel();
        btcancelar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        lbnome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setMaximumSize(new java.awt.Dimension(499, 569));
        setMinimumSize(new java.awt.Dimension(499, 569));

        txtnome.setToolTipText("");

        lbdtnascimento.setText("Data de Nascimento");
        lbdtnascimento.setFocusable(false);

        lbtelefone.setText("Telefone");

        lbendereco.setText("Endereço");

        lbbairro.setText("Bairro");

        lbcidade.setText("Cidade");

        lbrg.setText("RG");

        lbcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cliente.png"))); // NOI18N
        lbcliente.setText("Cliente");

        lbpesquisa.setText("Pesquisa");

        lbcpf.setText("CPF");

        rbnome.setSelected(true);
        rbnome.setText("Nome");

        rbcpf.setText("CPF");

        lbcnpj.setText("CNPJ");

        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyReleased(evt);
            }
        });

        jScrollPane1.setFocusable(false);

        tbcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF"
            }
        ));
        tbcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcliente);

        btsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.jpeg"))); // NOI18N
        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.jpg"))); // NOI18N
        btalterar.setText("Alterar");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        lbid.setText("ID");

        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        txtid.setEditable(false);
        txtid.setEnabled(false);

        lbnome.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lbcliente))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbpesquisa)
                            .addGap(18, 18, 18)
                            .addComponent(rbnome)
                            .addGap(18, 18, 18)
                            .addComponent(rbcpf)
                            .addGap(30, 30, 30)
                            .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbid, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbnome)
                                .addGap(18, 18, 18)
                                .addComponent(txtnome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbdtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbtelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btsalvar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btalterar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btcancelar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtrg, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(txtbairro))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbcpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbcidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtcpf, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addComponent(txtcidade)))
                                .addComponent(txtcnpj)
                                .addComponent(txtendereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbcliente)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbpesquisa)
                            .addComponent(rbnome)
                            .addComponent(rbcpf)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbid)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnome)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdtnascimento)
                    .addComponent(txtdtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtelefone)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbendereco)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbbairro)
                    .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcidade)
                    .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbrg)
                    .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcpf)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcnpj)
                    .addComponent(txtcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar)
                    .addComponent(btalterar)
                    .addComponent(btcancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    SimpleDateFormat formatador=new SimpleDateFormat("dd/MM/yyyy");
    private void txtpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyReleased
        // TODO add your handling code here:
        if(!txtpesquisa.getText().isEmpty()){
            List<Cliente> clientes;
            if(rbnome.isSelected()){
                clientes=new Cliente().listarNomeCpfPorNome(txtpesquisa.getText());
                tbcliente.setModel(getModelo(clientes));
            }
            else{
                if(txtpesquisa.getText().length()==11){
                    clientes=new Cliente().listarNomeCpfPorCpf(txtpesquisa.getText());
                    tbcliente.setModel(getModelo(clientes));
                }
            }
        }
    }//GEN-LAST:event_txtpesquisaKeyReleased

    private void tbclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbclienteMouseClicked
        // TODO add your handling code here:
        Integer linha=tbcliente.getSelectedRow();
        List<Cliente> clientes=new Cliente().listarPorCpf(tbcliente.getValueAt(linha, 1).toString());
        System.out.println("teste");
        if(clientes.size()>0){
            inserirValoresCliente(clientes.get(0));
        }
    }//GEN-LAST:event_tbclienteMouseClicked

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
        Cliente c=pegarDadosCampos();
        if(c!=null){
            if(c.salvar()){
                JOptionPane.showMessageDialog(rootPane, "Cliente salvo com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se esse cpf já está cadastrado no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
        // TODO add your handling code here:
        Cliente c=pegarDadosCampos();
        if(c!=null){
            if(c.alterar()){
                JOptionPane.showMessageDialog(rootPane, "Cliente alterado com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se esse cpf já está cadastrado no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btalterarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btcancelarActionPerformed

    public MaskFormatter pegarFormatterDate(){
        MaskFormatter mformat = null;
        try{
            mformat=new MaskFormatter("##/##/####");
            mformat.setPlaceholderCharacter('_');
        }
        catch(ParseException e){
            
        }
        return mformat;
    }
    
    
    
    
    
    public void inserirValoresCliente(Cliente c){
        txtid.setText(c.getId().toString());
        txtnome.setText(c.getNome());
        txtdtnascimento.setText(formatador.format(c.getDataNasc()));
        txttelefone.setText(c.getTelefone());
        txtendereco.setText(c.getEndereco());
        txtbairro.setText(c.getBairro());
        txtcidade.setText(c.getCidade());
        txtrg.setText(c.getRg());
        txtcpf.setText(c.getCpf());
        txtcnpj.setText(c.getCnpj());
        modoalteracao(true);
    }
    public void modoalteracao(Boolean b){
        btsalvar.setEnabled(!b);
        btalterar.setEnabled(b);
    }
    
    public void limparCampos(){
        rbnome.setSelected(true);
        txtpesquisa.setText("");
        txtid.setText("");
        txtnome.setText("");
        txtdtnascimento.setText("");
        txttelefone.setText("");
        txtendereco.setText("");
        txtbairro.setText("");
        txtcidade.setText("");
        txtrg.setText("");
        txtcpf.setText("");
        txtcnpj.setText("");
        modoalteracao(false);
        txtpesquisa.requestFocus();
    }
    
    public DefaultTableModel getModelo(List<Cliente> lista){
        Vector<String> headers=new Vector<String>();
        headers.add("Nome");
        headers.add("CPF");
        Vector<Object> vetorvalores=new Vector<Object>();
        for(Cliente c:lista){
            Vector vetor=new Vector();
            vetor.add(c.getNome());
            vetor.add(c.getCpf());
            vetorvalores.add(vetor);
        }
        return new DefaultTableModel(vetorvalores, headers);
    }
    
    public Boolean verificarCampos(){
        
        
        try {
            formatador.parse(txtdtnascimento.getText());
        } catch (ParseException ex) {
            return false;
        }
        return !txtnome.getText().isEmpty()&&
               !txttelefone.getText().isEmpty()&&
               !txtendereco.getText().isEmpty()&&
               !txtbairro.getText().isEmpty()&&
               !txtcidade.getText().isEmpty()&&
               !txtrg.getText().isEmpty()&&
               !(txtcpf.getText().isEmpty())&&
               txtcpf.getText().length()==11;
    }
    
    
    
    public Cliente pegarDadosCampos(){
        if(verificarCampos()){
            Integer id = null;
            Date dt = null;
            try {
                id=Integer.parseInt(txtid.getText());
            } 
            catch (Exception ex) {
                //pode ter tentado converter o id em integer no campo vazio(caso de salvar que não precisa de id).
            }
            try {
                dt=formatador.parse(txtdtnascimento.getText());
                return new Cliente(id, txtnome.getText(),
                               dt, txttelefone.getText(), txtendereco.getText(), 
                               txtbairro.getText(), txtcidade.getText(),
                               txtrg.getText(), txtcpf.getText(), txtcnpj.getText());
            } 
            catch (ParseException ex) {
                //campo não pode ser vazio, se der erro retorna null.
            }
        }
        return null;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btsalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbbairro;
    private javax.swing.JLabel lbcidade;
    private javax.swing.JLabel lbcliente;
    private javax.swing.JLabel lbcnpj;
    private javax.swing.JLabel lbcpf;
    private javax.swing.JLabel lbdtnascimento;
    private javax.swing.JLabel lbendereco;
    private javax.swing.JLabel lbid;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbpesquisa;
    private javax.swing.JLabel lbrg;
    private javax.swing.JLabel lbtelefone;
    private javax.swing.JRadioButton rbcpf;
    private javax.swing.JRadioButton rbnome;
    private javax.swing.JTable tbcliente;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcnpj;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtdtnascimento;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JTextField txtrg;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
