/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import BO.CategoriaProduto;
import BO.Conta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renan
 */
public class CadConta extends javax.swing.JFrame {

    /**
     * Creates new form CadConta
     */
    public CadConta() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbconta = new javax.swing.JLabel();
        lbpesquisa = new javax.swing.JLabel();
        rbid = new javax.swing.JRadioButton();
        rbdescricao = new javax.swing.JRadioButton();
        txtpesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbconta = new javax.swing.JTable();
        lbid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lbdescricao = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JTextField();
        lbvalorparcela = new javax.swing.JLabel();
        txtvalorparcela = new javax.swing.JTextField();
        lbnumparcelas = new javax.swing.JLabel();
        txtnumparcelas = new javax.swing.JTextField();
        lbdtcadastro = new javax.swing.JLabel();
        txtdtcadastro = new javax.swing.JFormattedTextField();
        lbdtvencimento = new javax.swing.JLabel();
        txtdtvencimento = new javax.swing.JFormattedTextField();
        btsalvar = new javax.swing.JButton();
        btalterar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Conta");
        setFocusable(false);

        lbconta.setText("Conta");

        lbpesquisa.setText("Pesquisa");

        buttonGroup1.add(rbid);
        rbid.setText("ID");

        buttonGroup1.add(rbdescricao);
        rbdescricao.setSelected(true);
        rbdescricao.setText("Descricao");

        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyReleased(evt);
            }
        });

        jScrollPane1.setFocusable(false);

        tbconta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Data Vencimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbconta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcontaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbconta);
        if (tbconta.getColumnModel().getColumnCount() > 0) {
            tbconta.getColumnModel().getColumn(0).setResizable(false);
            tbconta.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbconta.getColumnModel().getColumn(1).setResizable(false);
            tbconta.getColumnModel().getColumn(2).setResizable(false);
            tbconta.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        lbid.setText("ID");

        txtid.setEditable(false);
        txtid.setEnabled(false);

        lbdescricao.setText("Descrição");

        lbvalorparcela.setText("Valor Parcela");

        lbnumparcelas.setText("Numero de Parcelas");

        lbdtcadastro.setText("Data de Cadastro");

        lbdtvencimento.setText("Data de Vencimento");

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btalterar.setText("Alterar");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbvalorparcela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtvalorparcela)
                        .addGap(18, 18, 18)
                        .addComponent(lbnumparcelas)
                        .addGap(18, 18, 18)
                        .addComponent(txtnumparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbdescricao)
                            .addComponent(lbid))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid)
                            .addComponent(txtdescricao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbdtcadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btsalvar)
                                        .addGap(41, 41, 41)
                                        .addComponent(btalterar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtdtcadastro)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbdtvencimento)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btcancelar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(txtdtvencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbpesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(rbdescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbid)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpesquisa)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbconta)
                                .addGap(209, 209, 209)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbconta)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbpesquisa)
                    .addComponent(rbdescricao)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbid))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbid)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdescricao)
                    .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbvalorparcela)
                    .addComponent(txtvalorparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnumparcelas)
                    .addComponent(txtnumparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdtcadastro)
                    .addComponent(txtdtcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdtvencimento)
                    .addComponent(txtdtvencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar)
                    .addComponent(btalterar)
                    .addComponent(btcancelar))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    SimpleDateFormat formatador=new SimpleDateFormat("dd/MM/yyyy");
    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
        Conta c=pegarDadosCampos();
        if(c!=null){
            if(c.salvar()){
                JOptionPane.showMessageDialog(rootPane, "Conta salva com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se essa conta já está cadastrada no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
        // TODO add your handling code here:
        Conta c=pegarDadosCampos();
        if(c!=null){
            if(c.alterar()){
                JOptionPane.showMessageDialog(rootPane, "Conta alterada com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se essa conta já está cadastrada no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btalterarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void txtpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyReleased
        // TODO add your handling code here:
        if(!txtpesquisa.getText().isEmpty()){
            List<Conta> contas;
            if(rbdescricao.isSelected()){
                contas=new Conta().listarIdDescricaoDataPorDescricao(txtpesquisa.getText());
                tbconta.setModel(getModelo(contas));
            }
            else{
                Integer id=null;
                try{
                    id=Integer.parseInt(txtpesquisa.getText());
                    contas=new Conta().listarIdDescricaoDataPorId(id);
                    tbconta.setModel(getModelo(contas));
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Certifique-se de que digitou somente numeros inteiros \nsem espaço e sem qualquer caracter que não seja número","Caracteres invalidos",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_txtpesquisaKeyReleased

    private void tbcontaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcontaMouseClicked
        // TODO add your handling code here:
        Integer linha=tbconta.getSelectedRow();
        List<Conta> contas=new Conta().listarPorId(Integer.parseInt(tbconta.getValueAt(linha, 0).toString()));
        if(contas.size()>0){
            inserirValoresProduto(contas.get(0));
        }
    }//GEN-LAST:event_tbcontaMouseClicked

    public void inserirValoresProduto(Conta c){
        txtid.setText(Integer.toString(c.getId()));
        txtdescricao.setText(c.getDescricao());
        txtvalorparcela.setText(Double.toString(c.getValorParcela()));
        txtnumparcelas.setText(Integer.toString(c.getNumParcelas()));
        txtdtcadastro.setText(formatador.format(c.getDataCadastro()));
        txtdtvencimento.setText(formatador.format(c.getDataVencimento()));
        modoalteracao(true);
    }
    public void modoalteracao(Boolean b){
        btsalvar.setEnabled(!b);
        btalterar.setEnabled(b);
    }
    
    public void limparCampos(){
        rbdescricao.setSelected(true);
        txtpesquisa.setText("");
        txtid.setText("");
        txtdescricao.setText("");
        txtvalorparcela.setText("");
        txtnumparcelas.setText("");
        txtdtcadastro.setText("");
        txtdtvencimento.setText("");
        modoalteracao(false);
        txtpesquisa.requestFocus();
    }
    
    public DefaultTableModel getModelo(List<Conta> lista){
        Vector<String> headers=new Vector<String>();
        headers.add("ID");
        headers.add("Descrição");
        headers.add("Data Vencimento");
        Vector<Object> vetorvalores=new Vector<Object>();
        for(Conta c:lista){
            Vector vetor=new Vector();
            vetor.add(c.getId());
            vetor.add(c.getDescricao());
            vetor.add(formatador.format(c.getDataVencimento()));
            vetorvalores.add(vetor);
        }
        return new DefaultTableModel(vetorvalores, headers);
    }
    
    public Boolean verificarCampos(){
        return !txtdescricao.getText().isEmpty()&&
               !txtvalorparcela.getText().isEmpty()&&
               !txtnumparcelas.getText().isEmpty()&&
                txtdtcadastro.getText().length()==10 &&
                txtdtvencimento.getText().length()==10;
    }
    
    public Conta pegarDadosCampos(){
        if(verificarCampos()){
            Integer id = null;
            Date dtcadastro = null;
            Date dtvencimento = null;
            Double valorparcela = null;
            Integer numparcelas = null;
            
            try {
                id=Integer.parseInt(txtid.getText());
            } 
            catch (Exception e) {
                //caracteres invalidos ou campo vazio
            }
            try {
                dtcadastro=formatador.parse(txtdtcadastro.getText());
                dtvencimento=formatador.parse(txtdtvencimento.getText());
                valorparcela=Double.parseDouble(txtvalorparcela.getText());
                numparcelas=Integer.parseInt(txtnumparcelas.getText());
                return new Conta(id, txtdescricao.getText(), valorparcela, numparcelas, dtcadastro, dtvencimento);
            } catch (ParseException ex) {
                
            }
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbconta;
    private javax.swing.JLabel lbdescricao;
    private javax.swing.JLabel lbdtcadastro;
    private javax.swing.JLabel lbdtvencimento;
    private javax.swing.JLabel lbid;
    private javax.swing.JLabel lbnumparcelas;
    private javax.swing.JLabel lbpesquisa;
    private javax.swing.JLabel lbvalorparcela;
    private javax.swing.JRadioButton rbdescricao;
    private javax.swing.JRadioButton rbid;
    private javax.swing.JTable tbconta;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtdtcadastro;
    private javax.swing.JTextField txtdtvencimento;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnumparcelas;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JTextField txtvalorparcela;
    // End of variables declaration//GEN-END:variables
}
