/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import BO.FormaPagamento;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renan
 */
public class CadFormaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form CadFormaPagamento
     */
    public CadFormaPagamento() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbformapagamento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbformapag = new javax.swing.JTable();
        lbid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lbformapag = new javax.swing.JLabel();
        rbcartao = new javax.swing.JRadioButton();
        rbdinheiro = new javax.swing.JRadioButton();
        lbtipocartao = new javax.swing.JLabel();
        rbcredito = new javax.swing.JRadioButton();
        rbdebito = new javax.swing.JRadioButton();
        lbnumparcelas = new javax.swing.JLabel();
        txtnumparcelas = new javax.swing.JTextField();
        lbtaxajuros = new javax.swing.JLabel();
        txttaxajuros = new javax.swing.JTextField();
        btsalvar = new javax.swing.JButton();
        btalterar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        rbnenhum = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Forma de Pagamento");
        setMaximumSize(new java.awt.Dimension(523, 497));
        setMinimumSize(new java.awt.Dimension(523, 497));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbformapagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartao.png"))); // NOI18N
        lbformapagamento.setText("Forma de Pagamento");

        jScrollPane1.setFocusable(false);

        tbformapag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbformapag.setFocusable(false);
        tbformapag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbformapagMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbformapag);

        lbid.setText("ID");

        txtid.setEditable(false);
        txtid.setEnabled(false);

        lbformapag.setText("Forma de pagamento");

        buttonGroup1.add(rbcartao);
        rbcartao.setSelected(true);
        rbcartao.setText("Cartão");

        buttonGroup1.add(rbdinheiro);
        rbdinheiro.setText("Dinheiro");
        rbdinheiro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbdinheiroItemStateChanged(evt);
            }
        });

        lbtipocartao.setText("Tipo de Cartão");

        buttonGroup2.add(rbcredito);
        rbcredito.setSelected(true);
        rbcredito.setText("Credito");

        buttonGroup2.add(rbdebito);
        rbdebito.setText("Debito");

        lbnumparcelas.setText("Numero de Parcelas");

        lbtaxajuros.setText("Taxa de Juros");

        btsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.jpeg"))); // NOI18N
        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.jpg"))); // NOI18N
        btalterar.setText("Alterar");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbnenhum);
        rbnenhum.setText("Nenhum (Dinheiro)");
        rbnenhum.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbtipocartao)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(lbnumparcelas)))
                                    .addGap(255, 255, 255))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbformapag)
                                        .addComponent(lbid))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtnumparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbtaxajuros)
                                            .addGap(18, 18, 18)
                                            .addComponent(txttaxajuros, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbcartao)
                                                .addComponent(rbcredito))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbdinheiro)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rbdebito)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rbnenhum))))
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(lbformapagamento))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btsalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btalterar)
                        .addGap(18, 18, 18)
                        .addComponent(btcancelar)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbformapagamento)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbid)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbformapag)
                    .addComponent(rbdinheiro)
                    .addComponent(rbcartao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtipocartao)
                    .addComponent(rbcredito)
                    .addComponent(rbdebito)
                    .addComponent(rbnenhum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnumparcelas)
                    .addComponent(txtnumparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtaxajuros)
                    .addComponent(txttaxajuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btalterar)
                    .addComponent(btcancelar)
                    .addComponent(btsalvar))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
        // TODO add your handling code here:
        FormaPagamento fp=pegarDadosCampos();
        if(fp!=null){
            if(fp.alterar()){
                JOptionPane.showMessageDialog(rootPane, "Forma de pagamento alterada com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se essa forma de pagamento já está cadastrado no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btalterarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void tbformapagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbformapagMouseClicked
        // TODO add your handling code here:
        Integer linha=tbformapag.getSelectedRow();
        /*List<FormaPagamento> listaformas=new FormaPagamento().listarPorId(Integer.parseInt(tbformapag.getValueAt(linha, 0).toString()));
        if(listaformas.size()>0){
            inserirValoresFormaPagamento(listaformas.get(0));
        }*/
        
        txtid.setText(tbformapag.getValueAt(linha, 0).toString());
        if(tbformapag.getValueAt(linha, 1).toString().equals("Cartão")){
            rbcartao.setSelected(true);
            if(tbformapag.getValueAt(linha, 2).toString().equals("Credito")){
                rbcredito.setSelected(true);
            }
            else{
                rbdebito.setSelected(true);
            }
        }
        else{
            rbdinheiro.setSelected(true);
        }
        txtnumparcelas.setText(tbformapag.getValueAt(linha, 3).toString());
        txttaxajuros.setText(tbformapag.getValueAt(linha, 4).toString());
        modoalteracao(true);
        
        
        
    }//GEN-LAST:event_tbformapagMouseClicked

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
        FormaPagamento fp=pegarDadosCampos();
        if(fp!=null){
            if(fp.salvar()){
                JOptionPane.showMessageDialog(rootPane, "Forma de pagamento salva com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se essa forma de pagamento já está cadastrado no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void rbdinheiroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbdinheiroItemStateChanged
        // TODO add your handling code here:
        Boolean b=rbdinheiro.isSelected();
        if(b){
            rbcredito.setEnabled(!b);
            rbdebito.setEnabled(!b);
            rbnenhum.setSelected(b);
            txtnumparcelas.setText("1");
            txtnumparcelas.setEnabled(!b);
            txtnumparcelas.setEditable(!b);
        }
        else{
            rbcredito.setSelected(!b);
            rbcredito.setEnabled(!b);
            rbdebito.setEnabled(!b);
            txtnumparcelas.setEnabled(!b);
            txtnumparcelas.setEditable(!b);
        }
        
    }//GEN-LAST:event_rbdinheiroItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tbformapag.setModel(getModelo(new FormaPagamento().listar()));
    }//GEN-LAST:event_formWindowOpened

    public void inserirValoresFormaPagamento(FormaPagamento fp){
        txtid.setText(fp.getId().toString());
        rbcartao.setSelected(fp.getCartao());
        if(fp.getTipoCartao()){
            rbcredito.setSelected(true);
        }
        else if(!fp.getTipoCartao()){
            rbdebito.setSelected(false);
        }
        txtnumparcelas.setText(Integer.toString(fp.getNumParcelas()));
        txttaxajuros.setText(Double.toString(fp.getTaxaJuros()));
        modoalteracao(true);
    }
    public void modoalteracao(Boolean b){
        btsalvar.setEnabled(!b);
        btalterar.setEnabled(b);
    }
    
    public void limparCampos(){
        txtid.setText("");
        rbcartao.setSelected(true);
        rbcredito.setSelected(true);
        txtnumparcelas.setText("");
        txttaxajuros.setText("");
        modoalteracao(false);
        tbformapag.setModel(getModelo(new FormaPagamento().listar()));
    }
    
    public DefaultTableModel getModelo(List<FormaPagamento> lista){
        Vector<String> headers=new Vector<String>();
        headers.add("Id");
        headers.add("Forma");
        headers.add("Tipo");
        headers.add("Parcelas");
        headers.add("Taxa Juros");
        
        Vector<Object> vetorvalores=new Vector<Object>();
        for(FormaPagamento fp:lista){
            Vector vetor=new Vector();
            vetor.add(fp.getId());
            vetor.add((fp.getCartao())?"Cartão":"Dinheiro");
            vetor.add((fp.getCartao())?(fp.getTipoCartao())?"Credito":"Debito":"Dinheiro");
            vetor.add(fp.getNumParcelas());
            vetor.add(fp.getTaxaJuros());
            vetorvalores.add(vetor);
        }
        return new DefaultTableModel(vetorvalores, headers);
    }
    
    public Boolean verificarCampos(){
        Double taxajuros;
        try{
            taxajuros=Double.parseDouble(txttaxajuros.getText());
        }
        catch(Exception e){
            return null;
        }
        return !txtnumparcelas.getText().isEmpty() &&
               !txttaxajuros.getText().isEmpty();
    }
    
    public FormaPagamento pegarDadosCampos(){
        if(verificarCampos()){
            Integer id = null;
            try {
                id=Integer.parseInt(txtid.getText());
            } 
            catch (Exception ex) {
                //caracteres invalidos ou campo vazio
            }
            return new FormaPagamento(id, rbcartao.isSelected(), rbcredito.isSelected(), Integer.parseInt(txtnumparcelas.getText()), Double.parseDouble(txttaxajuros.getText()));
            //return new FormaPagamento(id, rbcartao.isSelected(), (rbcredito.isSelected())?true:(rbdebito.isSelected())?false:null, Integer.parseInt(txtnumparcelas.getText()), Double.parseDouble(txttaxajuros.getText()));
        }
        return null;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFormaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFormaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbformapag;
    private javax.swing.JLabel lbformapagamento;
    private javax.swing.JLabel lbid;
    private javax.swing.JLabel lbnumparcelas;
    private javax.swing.JLabel lbtaxajuros;
    private javax.swing.JLabel lbtipocartao;
    private javax.swing.JRadioButton rbcartao;
    private javax.swing.JRadioButton rbcredito;
    private javax.swing.JRadioButton rbdebito;
    private javax.swing.JRadioButton rbdinheiro;
    private javax.swing.JRadioButton rbnenhum;
    private javax.swing.JTable tbformapag;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnumparcelas;
    private javax.swing.JTextField txttaxajuros;
    // End of variables declaration//GEN-END:variables
}
