/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import BO.Cargo;
import BO.Cliente;
import BO.Funcionario;
import BO.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Renan
 */
public class CadFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadCliente
     */
    public CadFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbcliente = new javax.swing.JLabel();
        lbpesquisa = new javax.swing.JLabel();
        rbnome = new javax.swing.JRadioButton();
        rbcpf = new javax.swing.JRadioButton();
        txtpesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcliente = new javax.swing.JTable();
        lbid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lbnome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        lbdtnascimento = new javax.swing.JLabel();
        txtdtnascimento = new javax.swing.JFormattedTextField(pegarFormatterDate());
        lbtelefone = new javax.swing.JLabel();
        txttelefone = new javax.swing.JTextField();
        lbendereco = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        lbbairro = new javax.swing.JLabel();
        txtbairro = new javax.swing.JTextField();
        lbcidade = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        lbrg = new javax.swing.JLabel();
        txtrg = new javax.swing.JTextField();
        lbcpf = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        lbcnpj = new javax.swing.JLabel();
        txtcnpj = new javax.swing.JTextField();
        lbcargo = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        cbcargo = new javax.swing.JComboBox();
        lbusuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lbsenha = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        lbemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lbsalario = new javax.swing.JLabel();
        txtsalario = new javax.swing.JTextField();
        btsalvar = new javax.swing.JButton();
        btalterar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionario");
        setMaximumSize(new java.awt.Dimension(657, 607));
        setMinimumSize(new java.awt.Dimension(657, 607));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario.png"))); // NOI18N
        lbcliente.setText("Funcionario");

        lbpesquisa.setText("Pesquisa");

        buttonGroup1.add(rbnome);
        rbnome.setSelected(true);
        rbnome.setText("Nome");

        buttonGroup1.add(rbcpf);
        rbcpf.setText("CPF");

        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyReleased(evt);
            }
        });

        jScrollPane1.setFocusable(false);

        tbcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF"
            }
        ));
        tbcliente.setFocusable(false);
        tbcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcliente);

        lbid.setText("ID");

        txtid.setEditable(false);
        txtid.setEnabled(false);

        lbnome.setText("Nome");

        txtnome.setToolTipText("");

        lbdtnascimento.setText("Data de Nascimento");

        lbtelefone.setText("Telefone");

        lbendereco.setText("Endereço");

        lbbairro.setText("Bairro");

        lbcidade.setText("Cidade");

        lbrg.setText("RG");

        lbcpf.setText("CPF");

        lbcnpj.setText("CNPJ (opcional)");

        lbcargo.setText("Cargo");

        txtcargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcargoFocusLost(evt);
            }
        });
        txtcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcargoKeyReleased(evt);
            }
        });

        cbcargo.setFocusable(false);

        lbusuario.setText("Usuário");

        lbsenha.setText("Senha");

        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });

        lbemail.setText("Email");

        lbsalario.setText("Salário");

        btsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.jpeg"))); // NOI18N
        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.jpg"))); // NOI18N
        btalterar.setText("Alterar");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbnome)
                                .addGap(10, 10, 10)
                                .addComponent(rbcpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbnome)
                                .addGap(18, 18, 18)
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbdtnascimento)
                                .addGap(18, 18, 18)
                                .addComponent(txtdtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbbairro)
                                            .addComponent(lbrg))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtbairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(lbcidade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbemail)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbsalario)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtendereco, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtcidade)
                                    .addComponent(txtcpf)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbcargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtsenha)
                                    .addComponent(txtsalario)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbtelefone)
                                .addGap(18, 18, 18)
                                .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbendereco)
                                    .addComponent(lbcpf)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbusuario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtusuario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbcnpj)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbcargo)
                                    .addComponent(lbsenha))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btsalvar)
                        .addGap(31, 31, 31)
                        .addComponent(btalterar)
                        .addGap(35, 35, 35)
                        .addComponent(btcancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lbcliente)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbcliente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbpesquisa)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbnome)
                    .addComponent(rbcpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbid)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnome)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdtnascimento)
                    .addComponent(txtdtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtelefone)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbendereco)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbbairro)
                    .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcidade)
                    .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbrg)
                    .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcpf)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcnpj)
                    .addComponent(txtcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcargo)
                    .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbusuario)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsenha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsalario)
                    .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar)
                    .addComponent(btalterar)
                    .addComponent(btcancelar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    SimpleDateFormat formatador=new SimpleDateFormat("dd/MM/yyyy");
    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
        Funcionario f=pegarDadosCampos();
        if(f!=null){
            System.out.println(f.getCargoId().getId()+" "+f.getCargoId().getNome());
            if(f.salvar()){
                JOptionPane.showMessageDialog(rootPane, "Funcionário salvo com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se esse cpf já está cadastrado no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
        // TODO add your handling code here:
        Funcionario f=pegarDadosCampos();
        if(f!=null){
            if(f.alterar()){
                JOptionPane.showMessageDialog(rootPane, "Funcionário alterado com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se esse cpf já está cadastrado no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btalterarActionPerformed

    private void txtpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyReleased
        // TODO add your handling code here:
        if(!txtpesquisa.getText().isEmpty()){
            List<Cliente> funcionarios;
            if(rbnome.isSelected()){
                funcionarios=new Cliente().listarNomeCpfPorNome(txtpesquisa.getText());
                tbcliente.setModel(getModelo(funcionarios));
            }
            else{
                if(txtpesquisa.getText().length()==11){
                    funcionarios=new Cliente().listarNomeCpfPorCpf(txtpesquisa.getText());
                    tbcliente.setModel(getModelo(funcionarios));
                }
            }
        }
    }//GEN-LAST:event_txtpesquisaKeyReleased

    private void tbclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbclienteMouseClicked
        // TODO add your handling code here:
        Integer linha=tbcliente.getSelectedRow();
        List<Funcionario> funcionarios=new Funcionario().listarPorCpf(tbcliente.getValueAt(linha, 1).toString());
        try{
            inserirValoresFuncionario(funcionarios.get(0));
        }
        catch(Exception e){
            limparCampos();
            Cliente cliente=new Cliente().listarPorCpf(tbcliente.getValueAt(linha, 1).toString()).get(0);
            inserirValoresCliente(cliente);
            
            
        }
    }//GEN-LAST:event_tbclienteMouseClicked

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        modoalteracao(false);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void txtcargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcargoKeyReleased
        // TODO add your handling code here:
        cbcargo.setModel(new DefaultComboBoxModel(new Cargo().listarPorNome(txtcargo.getText()).toArray()));
        
    }//GEN-LAST:event_txtcargoKeyReleased

    private void txtcargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcargoFocusLost
        // TODO add your handling code here:
        txtcargo.setText(cbcargo.getSelectedItem().toString());
    }//GEN-LAST:event_txtcargoFocusLost

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    
    public MaskFormatter pegarFormatterDate(){
        MaskFormatter mformat = null;
        try{
            mformat=new MaskFormatter("##/##/####");
            mformat.setPlaceholderCharacter('_');
        }
        catch(ParseException e){
            
        }
        return mformat;
    }
    
    
    
    
    
    public void inserirValoresFuncionario(Funcionario f){
        txtid.setText(f.getId().toString());
        inserirValoresCliente(f.getClienteId());
        txtcargo.setText(f.getCargoId().getNome());
        cbcargo.setModel(new DefaultComboBoxModel(new Object[]{f.getCargoId()}));
        txtusuario.setText(f.getUsuarioId().getNomeUsuario());
        txtsenha.setText(f.getUsuarioId().getSenha());
        txtemail.setText(f.getUsuarioId().getEmail());
        txtsalario.setText(f.getSalario().toString());
        txtnome.requestFocus();
        modoalteracao(true);
    }
    
    public void inserirValoresCliente(Cliente c){
        txtnome.setText(c.getNome());
        txtdtnascimento.setText(formatador.format(c.getDataNasc()));
        txttelefone.setText(c.getTelefone());
        txtendereco.setText(c.getEndereco());
        txtbairro.setText(c.getBairro());
        txtcidade.setText(c.getCidade());
        txtrg.setText(c.getRg());
        txtcpf.setText(c.getCpf());
        txtcnpj.setText(c.getCnpj());
        txtcargo.requestFocus();
        modoalteracao(false);
    }
    
    public void modoalteracao(Boolean b){
        txtusuario.setEnabled(!b);
        txtsenha.setEnabled(!b);
        txtemail.setEnabled(!b);
        btsalvar.setEnabled(!b);
        btalterar.setEnabled(b);
    }
    
    public void limparCampos(){
        rbnome.setSelected(true);
        txtpesquisa.setText("");
        txtid.setText("");
        txtnome.setText("");
        txtdtnascimento.setText("");
        txttelefone.setText("");
        txtendereco.setText("");
        txtbairro.setText("");
        txtcidade.setText("");
        txtrg.setText("");
        txtcpf.setText("");
        txtcnpj.setText("");
        txtcargo.setText("");
        cbcargo.removeAllItems();
        txtusuario.setText("");
        txtsenha.setText("");
        txtemail.setText("");
        txtsalario.setText("");
        
        modoalteracao(false);
        txtpesquisa.requestFocus();
    }
    
    public DefaultTableModel getModelo(List<Cliente> lista){
        Vector<String> headers=new Vector<String>();
        headers.add("Nome");
        headers.add("CPF");
        Vector<Object> vetorvalores=new Vector<Object>();
        for(Cliente c:lista){
            Vector vetor=new Vector();
            vetor.add(c.getNome());
            vetor.add(c.getCpf());
            vetorvalores.add(vetor);
        }
        return new DefaultTableModel(vetorvalores, headers);
    }
    
    public Boolean verificarCampos(){
        try {
            formatador.parse(txtdtnascimento.getText());
        } catch (ParseException ex) {
            return false;
        }
        try{
            Double salario=Double.parseDouble(txtsalario.getText());
        }
        catch(Exception e){
            return false;
        }
        return !txtnome.getText().isEmpty()&&
               !txttelefone.getText().isEmpty()&&
               !txtendereco.getText().isEmpty()&&
               !txtbairro.getText().isEmpty()&&
               !txtcidade.getText().isEmpty()&&
               !cbcargo.getSelectedItem().toString().isEmpty()&&
               !txtusuario.getText().isEmpty()&&
               !txtsenha.getText().isEmpty()&&
               !txtemail.getText().isEmpty();
    }
    
    
    
    public Funcionario pegarDadosCampos(){
        if(verificarCampos()){
            Integer id = null;
            Date dt = null;
            try {
                id=Integer.parseInt(txtid.getText());
            } 
            catch (Exception ex) {
                //pode ter tentado converter o id em integer no campo vazio(caso de salvar que não precisa de id).
            }
            try {
                dt=formatador.parse(txtdtnascimento.getText());
                
                Cliente cliente=new Cliente(null, txtnome.getText(),
                               dt, txttelefone.getText(), txtendereco.getText(), 
                               txtbairro.getText(), txtcidade.getText(),
                               txtrg.getText(), txtcpf.getText(), txtcnpj.getText());
                Cargo cargo=(Cargo)cbcargo.getSelectedItem();
                Usuario usuario=new Usuario(null, txtusuario.getText(), txtsenha.getText(), txtemail.getText());
                Funcionario funcionario=new Funcionario(id, Double.parseDouble(txtsalario.getText()), cargo, cliente, usuario);
                return funcionario;
                
            } 
            catch (ParseException ex) {
                //campo não pode ser vazio, se der erro retorna null.
            }
        }
        return null;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbcargo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbbairro;
    private javax.swing.JLabel lbcargo;
    private javax.swing.JLabel lbcidade;
    private javax.swing.JLabel lbcliente;
    private javax.swing.JLabel lbcnpj;
    private javax.swing.JLabel lbcpf;
    private javax.swing.JLabel lbdtnascimento;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbendereco;
    private javax.swing.JLabel lbid;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbpesquisa;
    private javax.swing.JLabel lbrg;
    private javax.swing.JLabel lbsalario;
    private javax.swing.JLabel lbsenha;
    private javax.swing.JLabel lbtelefone;
    private javax.swing.JLabel lbusuario;
    private javax.swing.JRadioButton rbcpf;
    private javax.swing.JRadioButton rbnome;
    private javax.swing.JTable tbcliente;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcnpj;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtdtnascimento;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JTextField txtrg;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txttelefone;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
