/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import BO.Usuario;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renan
 */
public class CadUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadUsuario
     */
    public CadUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbusuario = new javax.swing.JLabel();
        lbpesquisa = new javax.swing.JLabel();
        rbnome = new javax.swing.JRadioButton();
        rbemail = new javax.swing.JRadioButton();
        txtpesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbusuario = new javax.swing.JTable();
        lbid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lbnome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        lbsenha = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        lbemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btsalvar = new javax.swing.JButton();
        btalterar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbusuario.setText("Usuario");

        lbpesquisa.setText("Pesquisa");

        buttonGroup1.add(rbnome);
        rbnome.setSelected(true);
        rbnome.setText("Nome");

        buttonGroup1.add(rbemail);
        rbemail.setText("Email");

        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyReleased(evt);
            }
        });

        tbusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email"
            }
        ));
        tbusuario.setFocusable(false);
        tbusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbusuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbusuario);

        lbid.setText("ID");

        lbnome.setText("Nome de Usuário");

        lbsenha.setText("Senha");

        lbemail.setText("Email");

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btalterar.setText("Alterar");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lbusuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbpesquisa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbnome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbemail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbnome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtnome))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbid)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbsenha)
                                        .addComponent(lbemail))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtsenha)
                                        .addComponent(txtemail))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btsalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btalterar)
                        .addGap(18, 18, 18)
                        .addComponent(btcancelar)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lbusuario)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbpesquisa)
                    .addComponent(rbnome)
                    .addComponent(rbemail)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbid)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsenha)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar)
                    .addComponent(btalterar)
                    .addComponent(btcancelar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
        Usuario u=pegarDadosCampos();
        if(u!=null){
            if(u.salvar()){
                JOptionPane.showMessageDialog(rootPane, "Usuario salvo com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se esse usuário já está cadastrado no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
        // TODO add your handling code here:
        Usuario u=pegarDadosCampos();
        if(u!=null){
            if(u.alterar()){
                JOptionPane.showMessageDialog(rootPane, "Usuario salvo com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se esse usuário já está cadastrado no sistema", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btalterarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void txtpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyReleased
        // TODO add your handling code here:
        if(!txtpesquisa.getText().isEmpty()){
            List<Usuario> usuarios;
            if(rbnome.isSelected()){
                usuarios=new Usuario().listarIdNomeEmailPorNome(txtpesquisa.getText());
                tbusuario.setModel(getModelo(usuarios));
            }
            else{
                usuarios=new Usuario().listarIdNomeEmailPorEmail(txtpesquisa.getText());
                tbusuario.setModel(getModelo(usuarios));
            }
        }
    }//GEN-LAST:event_txtpesquisaKeyReleased

    private void tbusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbusuarioMouseClicked
        // TODO add your handling code here:
        Integer linha=tbusuario.getSelectedRow();
        List<Usuario> usuarios=new Usuario().listarPorId(Integer.parseInt(tbusuario.getValueAt(linha, 0).toString()));
        if(usuarios.size()>0){
            inserirValoresUsuario(usuarios.get(0));
        }
    }//GEN-LAST:event_tbusuarioMouseClicked
    
    public void inserirValoresUsuario(Usuario u){
        txtid.setText(u.getId().toString());
        txtnome.setText(u.getNomeUsuario());
        txtsenha.setText(u.getSenha());
        txtemail.setText(u.getEmail());
        modoalteracao(true);
    }
    public void modoalteracao(Boolean b){
        btsalvar.setEnabled(!b);
        btalterar.setEnabled(b);
    }
    
    public void limparCampos(){
        rbnome.setSelected(true);
        txtpesquisa.setText("");
        txtid.setText("");
        txtnome.setText("");
        txtsenha.setText("");
        txtemail.setText("");
        modoalteracao(false);
        txtpesquisa.requestFocus();
    }
    
    public DefaultTableModel getModelo(List<Usuario> lista){
        Vector<String> headers=new Vector<String>();
        headers.add("Id");
        headers.add("Nome");
        headers.add("Email");
        Vector<Object> vetorvalores=new Vector<Object>();
        for(Usuario u:lista){
            Vector vetor=new Vector();
            vetor.add(u.getId());
            vetor.add(u.getNomeUsuario());
            vetor.add(u.getEmail());
            vetorvalores.add(vetor);
        }
        return new DefaultTableModel(vetorvalores, headers);
    }
    
    public Boolean verificarCampos(){
        return !txtnome.getText().isEmpty() &&
               !txtsenha.getText().isEmpty() &&
               !txtemail.getText().isEmpty();
    }
    
    public Usuario pegarDadosCampos(){
        if(verificarCampos()){
            Integer id = null;
            try {
                id=Integer.parseInt(txtid.getText());
            } 
            catch (NumberFormatException ex) {
                //caracteres invalidos ou campo vazio
            }
            return new Usuario(id, txtnome.getText(), txtsenha.getText(), txtemail.getText());
        }
        return null;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbid;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbpesquisa;
    private javax.swing.JLabel lbsenha;
    private javax.swing.JLabel lbusuario;
    private javax.swing.JRadioButton rbemail;
    private javax.swing.JRadioButton rbnome;
    private javax.swing.JTable tbusuario;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
