/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import BO.CategoriaProduto;
import BO.Cliente;
import BO.Estoque;
import BO.EstoqueVenda;
import BO.FormaPagamento;
import BO.Produto;
import BO.Venda;
import dao.ClienteDao;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renan
 */
public class Vendas extends javax.swing.JFrame {

    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbvenda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbinfocliente = new javax.swing.JLabel();
        lbpesquisa = new javax.swing.JLabel();
        txtpesquisacliente = new javax.swing.JTextField();
        cbpesquisacliente = new javax.swing.JComboBox();
        panelproduto = new javax.swing.JPanel();
        lbinfoprodutos = new javax.swing.JLabel();
        lbcodproduto = new javax.swing.JLabel();
        txtcodproduto = new javax.swing.JTextField();
        lbcategoria = new javax.swing.JLabel();
        cbcategoria = new javax.swing.JComboBox();
        lbnomeproduto = new javax.swing.JLabel();
        txtnomeproduto = new javax.swing.JTextField();
        cbnomeproduto = new javax.swing.JComboBox();
        lbvalorunitario = new javax.swing.JLabel();
        txtvalorunitario = new javax.swing.JTextField();
        lbqtdproduto = new javax.swing.JLabel();
        txtqtdproduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproduto = new javax.swing.JTable();
        btconfirmardadosvenda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbinfopagamento = new javax.swing.JLabel();
        lbsubtotal = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JFormattedTextField();
        lbdesconto = new javax.swing.JLabel();
        txtdesconto = new javax.swing.JTextField();
        btaplicar = new javax.swing.JButton();
        lbformapag = new javax.swing.JLabel();
        rbdinheiro = new javax.swing.JRadioButton();
        rbcredito = new javax.swing.JRadioButton();
        rbdebito = new javax.swing.JRadioButton();
        lbnumparcelas = new javax.swing.JLabel();
        cbnumparcelas = new javax.swing.JComboBox();
        lbtaxajuros = new javax.swing.JLabel();
        txttaxajuros = new javax.swing.JTextField();
        lbtotal = new javax.swing.JLabel();
        txttotal = new javax.swing.JFormattedTextField();
        lbvalorpago = new javax.swing.JLabel();
        txtvalorpago = new javax.swing.JFormattedTextField();
        lbtroco = new javax.swing.JLabel();
        txttroco = new javax.swing.JFormattedTextField();
        btefetuarvenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");
        setMaximumSize(new java.awt.Dimension(818, 700));
        setMinimumSize(new java.awt.Dimension(818, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel4.setLayout(null);

        lbvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vendas.png"))); // NOI18N
        lbvenda.setText("Venda");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbinfocliente.setText("Informações do Cliente (Opcional)");

        lbpesquisa.setText("Pesquisa (CPF)");

        txtpesquisacliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisaclienteKeyReleased(evt);
            }
        });

        cbpesquisacliente.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbpesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpesquisacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(cbpesquisacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lbinfocliente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbinfocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbpesquisa)
                    .addComponent(cbpesquisacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        panelproduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbinfoprodutos.setText("Informações dos Produtos");

        lbcodproduto.setText("Codigo");

        txtcodproduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcodprodutoFocusLost(evt);
            }
        });
        txtcodproduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodprodutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodprodutoKeyReleased(evt);
            }
        });

        lbcategoria.setText("Categoria");

        cbcategoria.setFocusable(false);
        cbcategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbcategoriaItemStateChanged(evt);
            }
        });

        lbnomeproduto.setText("Nome");

        txtnomeproduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomeprodutoFocusLost(evt);
            }
        });
        txtnomeproduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomeprodutoKeyReleased(evt);
            }
        });

        cbnomeproduto.setFocusable(false);

        lbvalorunitario.setText("Valor (R$)");

        txtvalorunitario.setEditable(false);
        txtvalorunitario.setEnabled(false);

        lbqtdproduto.setText("Qtde");

        txtqtdproduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtqtdprodutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtqtdprodutoKeyReleased(evt);
            }
        });

        jScrollPane1.setFocusable(false);

        tbproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Valor Unit.", "Qtde.", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbproduto.setFocusable(false);
        tbproduto.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(tbproduto);
        if (tbproduto.getColumnModel().getColumnCount() > 0) {
            tbproduto.getColumnModel().getColumn(0).setResizable(false);
            tbproduto.getColumnModel().getColumn(1).setResizable(false);
            tbproduto.getColumnModel().getColumn(2).setResizable(false);
            tbproduto.getColumnModel().getColumn(3).setResizable(false);
            tbproduto.getColumnModel().getColumn(3).setPreferredWidth(40);
            tbproduto.getColumnModel().getColumn(4).setResizable(false);
        }

        btconfirmardadosvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entrar.png"))); // NOI18N
        btconfirmardadosvenda.setText("Fechar Pedido");
        btconfirmardadosvenda.setEnabled(false);
        btconfirmardadosvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconfirmardadosvendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelprodutoLayout = new javax.swing.GroupLayout(panelproduto);
        panelproduto.setLayout(panelprodutoLayout);
        panelprodutoLayout.setHorizontalGroup(
            panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprodutoLayout.createSequentialGroup()
                .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelprodutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(panelprodutoLayout.createSequentialGroup()
                                .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbcodproduto)
                                    .addComponent(lbnomeproduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtcodproduto)
                                    .addComponent(txtnomeproduto)
                                    .addComponent(cbnomeproduto, 0, 193, Short.MAX_VALUE))
                                .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelprodutoLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(lbvalorunitario))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprodutoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lbcategoria)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelprodutoLayout.createSequentialGroup()
                                        .addComponent(txtvalorunitario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbqtdproduto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtqtdproduto))
                                    .addComponent(cbcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelprodutoLayout.createSequentialGroup()
                        .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelprodutoLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(lbinfoprodutos))
                            .addGroup(panelprodutoLayout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(btconfirmardadosvenda)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelprodutoLayout.setVerticalGroup(
            panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprodutoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbinfoprodutos)
                .addGap(18, 18, 18)
                .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcodproduto)
                    .addComponent(txtcodproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcategoria)
                    .addComponent(cbcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbnomeproduto)
                        .addComponent(txtnomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbqtdproduto)
                        .addComponent(txtqtdproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtvalorunitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbvalorunitario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbnomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btconfirmardadosvenda)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelproduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lbvenda)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel4.add(jPanel3);
        jPanel3.setBounds(0, 0, 511, 690);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbinfopagamento.setText("Informações de Pagamento");

        lbsubtotal.setText("Sub-Total");

        txtsubtotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtsubtotal.setText("0.00");
        txtsubtotal.setEnabled(false);

        lbdesconto.setText("Desconto (%)");

        txtdesconto.setText("0");
        txtdesconto.setEnabled(false);

        btaplicar.setText("Aplicar");
        btaplicar.setEnabled(false);
        btaplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaplicarActionPerformed(evt);
            }
        });

        lbformapag.setText("Forma de Pagamento");

        buttonGroup1.add(rbdinheiro);
        rbdinheiro.setSelected(true);
        rbdinheiro.setText("Dinheiro");
        rbdinheiro.setEnabled(false);
        rbdinheiro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbdinheiroItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbcredito);
        rbcredito.setText("Cartão (Crédito)");
        rbcredito.setEnabled(false);
        rbcredito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbcreditoItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbdebito);
        rbdebito.setText("Cartão (Débito)");
        rbdebito.setEnabled(false);
        rbdebito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbdebitoItemStateChanged(evt);
            }
        });

        lbnumparcelas.setText("Nº de Parcelas");

        cbnumparcelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1x 0.00 juros: 0%" }));
        cbnumparcelas.setEnabled(false);
        cbnumparcelas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbnumparcelasItemStateChanged(evt);
            }
        });

        lbtaxajuros.setText("Taxa de juros (%)");

        txttaxajuros.setEditable(false);
        txttaxajuros.setText("0");
        txttaxajuros.setEnabled(false);

        lbtotal.setText("Total");

        txttotal.setEditable(false);
        txttotal.setText("0.00");
        txttotal.setEnabled(false);

        lbvalorpago.setText("Valor Pago");

        txtvalorpago.setText("0.00");
        txtvalorpago.setEnabled(false);
        txtvalorpago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvalorpagoKeyReleased(evt);
            }
        });

        lbtroco.setText("Troco");

        txttroco.setEditable(false);
        txttroco.setText("0.00");
        txttroco.setEnabled(false);

        btefetuarvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entrar.png"))); // NOI18N
        btefetuarvenda.setText("Efetuar Venda");
        btefetuarvenda.setEnabled(false);
        btefetuarvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btefetuarvendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btefetuarvenda)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbtotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbdesconto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbnumparcelas, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbtaxajuros, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbsubtotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbvalorpago, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbformapag, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(rbcredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(rbdinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(rbdebito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(cbnumparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txttaxajuros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txttotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtsubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(txtdesconto)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbtroco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttroco)
                                    .addComponent(txtvalorpago)
                                    .addComponent(btaplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbinfopagamento)
                        .addGap(55, 55, 55))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbinfopagamento)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdesconto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btaplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbformapag)
                    .addComponent(rbdinheiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbcredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbdebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbnumparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnumparcelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttaxajuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtaxajuros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvalorpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbvalorpago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtroco)
                    .addComponent(txttroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btefetuarvenda)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2);
        jPanel2.setBounds(520, 70, 270, 590);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 820, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DecimalFormat formatnumber=new DecimalFormat("#0.00");
            
    private void txtpesquisaclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaclienteKeyReleased
        // TODO add your handling code here:
        cbpesquisacliente.setModel(new DefaultComboBoxModel(new Cliente().listarPorCpf(txtpesquisacliente.getText()).toArray()));
    }//GEN-LAST:event_txtpesquisaclienteKeyReleased

    private void txtcodprodutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodprodutoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!txtcodproduto.getText().isEmpty()){
                List<Estoque> lista=new Estoque().listarPorCodBarra(Long.parseLong(txtcodproduto.getText()));
                if(!lista.isEmpty()){
                    Estoque estoque=lista.get(0);
                    cbcategoria.setModel(new DefaultComboBoxModel(new Object[]{estoque.getProduto().getCategoriaProduto()}));
                    txtnomeproduto.setText(estoque.getProduto().getNome());
                    cbnomeproduto.setModel(new DefaultComboBoxModel(new Object[]{estoque.getProduto()}));
                    txtvalorunitario.setText(formatnumber.format(estoque.getProduto().getValorUnitario()).replaceAll(",", "."));
                    txtqtdproduto.requestFocus();
                }
                else{
                    List<Produto> listaproduto=new Produto().listarPorId(Integer.parseInt(txtcodproduto.getText()));
                    if(!listaproduto.isEmpty()){
                    Produto prod=listaproduto.get(0);
                    cbcategoria.setModel(new DefaultComboBoxModel(new Object[]{prod.getCategoriaProduto()}));
                    txtnomeproduto.setText(prod.getNome());
                    cbnomeproduto.setModel(new DefaultComboBoxModel(new Object[]{prod}));
                    txtvalorunitario.setText(formatnumber.format(prod.getValorUnitario()).replaceAll(",", "."));
                    txtqtdproduto.requestFocus();
                }
                }
            }
            else{
                btconfirmardadosvenda.requestFocus();
            }
        }
    }//GEN-LAST:event_txtcodprodutoKeyPressed

    private void txtqtdprodutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtdprodutoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            Long codbarra=0L;
            DecimalFormat formatadornumber=new DecimalFormat("#000000000");
            formatadornumber.setMinimumIntegerDigits(9);
            formatadornumber.setMaximumIntegerDigits(9);
            if(txtcodproduto.getText().isEmpty()){
                Produto prod=((Produto)cbnomeproduto.getSelectedItem());
                prod.setCategoriaProduto((CategoriaProduto)cbcategoria.getSelectedItem());
                codbarra=prod.convertToCodBarra();
                txtcodproduto.setText(formatadornumber.format(codbarra));
            }
            Integer indice=null;
            for(int i=0; i<tbproduto.getRowCount(); i++){
                if(txtcodproduto.getText().equals(tbproduto.getValueAt(i, 0).toString())){
                    indice=i;
                    i=tbproduto.getRowCount();
                }
            }
            Integer qtdproduto=Integer.parseInt(txtqtdproduto.getText());
            Integer qtdprodutotabela=0;
            if(indice!=null){
                qtdprodutotabela=Integer.parseInt(tbproduto.getValueAt(indice, 3).toString());
            }
            Integer qtdprodutototal=qtdproduto+qtdprodutotabela;
            Estoque estoque=new Estoque().listarEstoquePorCodigoQuantidade(Long.parseLong(txtcodproduto.getText()), qtdprodutototal);
            if(estoque!=null){
                if(indice!=null){
                    ((DefaultTableModel)tbproduto.getModel()).removeRow(indice);
                }
                ((DefaultTableModel)tbproduto.getModel()).insertRow(0, new Object[]{txtcodproduto.getText(), cbnomeproduto.getSelectedItem(), formatnumber.format(estoque.getProduto().getValorUnitario()).replaceAll(",", "."), qtdprodutototal, formatnumber.format(estoque.getProduto().getValorUnitario()*qtdprodutototal).replaceAll(",",".")});
                
                txtsubtotal.setText(formatnumber.format(Double.parseDouble(txtsubtotal.getText())+estoque.getProduto().getValorUnitario()*qtdproduto).replaceAll(",", "."));
                txttotal.setText(txtsubtotal.getText());
                btconfirmardadosvenda.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Produto ou quantidade indisponível", "Erro ao inserir", JOptionPane.ERROR_MESSAGE);
            }
            txtcodproduto.setText("");
            txtnomeproduto.setText("");
            cbnomeproduto.setModel(new DefaultComboBoxModel());
            txtvalorunitario.setText("");
            txtqtdproduto.setText("");
            txtcodproduto.requestFocus();
            cbcategoria.setModel(new DefaultComboBoxModel(new CategoriaProduto().listarPorNome("").toArray()));
        }
    }//GEN-LAST:event_txtqtdprodutoKeyPressed

    private void txtqtdprodutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtdprodutoKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtqtdprodutoKeyReleased

    private void txtcodprodutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodprodutoKeyReleased
        // TODO add your handling code here:
        if (txtcodproduto.getText().length()==13) {
            List<Estoque> lista = new Estoque().listarPorCodBarra(Long.parseLong(txtcodproduto.getText()));
            try {
                Estoque estoque = lista.get(0);
                cbcategoria.setModel(new DefaultComboBoxModel(new Object[]{estoque.getProduto().getCategoriaProduto()}));
                txtnomeproduto.setText(estoque.getProduto().getNome());
                cbnomeproduto.setModel(new DefaultComboBoxModel(new Object[]{estoque.getProduto()}));
                txtvalorunitario.requestFocus();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_txtcodprodutoKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cbcategoria.setModel(new DefaultComboBoxModel(new CategoriaProduto().listarPorNome("").toArray()));
    }//GEN-LAST:event_formWindowOpened

    private void txtnomeprodutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeprodutoKeyReleased
        // TODO add your handling code here:
        if(txtcodproduto.getText().isEmpty() && !txtnomeproduto.getText().isEmpty()){
            List<Produto> lista=new Produto().listarIdNomeValorPorNomeCategoriaId(txtnomeproduto.getText(), ((CategoriaProduto)cbcategoria.getSelectedItem()).getId());
            if(lista!=null && lista.size()>0){
                cbnomeproduto.setModel(new DefaultComboBoxModel(lista.toArray()));
                txtvalorunitario.setText(formatnumber.format(lista.get(0).getValorUnitario()));
            }
            else{
                cbnomeproduto.setModel(new DefaultComboBoxModel(new Object[]{}));
                txtvalorunitario.setText("");
            }
        }
        else{
            cbnomeproduto.setModel(new DefaultComboBoxModel(new Object[]{}));
            txtvalorunitario.setText("");
        }
    }//GEN-LAST:event_txtnomeprodutoKeyReleased

    private void cbcategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbcategoriaItemStateChanged
        // TODO add your handling code here:
        txtnomeproduto.setText("");
        cbnomeproduto.removeAllItems();
        txtvalorunitario.setText("");
    }//GEN-LAST:event_cbcategoriaItemStateChanged

    private void btconfirmardadosvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconfirmardadosvendaActionPerformed
        // TODO add your handling code here:
        if(tbproduto.getRowCount()>0){
            modificarStatusCampos(true);
            cbnumparcelas.setModel(new DefaultComboBoxModel(new Object[]{"1x "+txtsubtotal.getText()+" juros: 0%"}));
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Insira pelo menos 1 produto para confirmação de dados da venda", "Erro ao confirmar dados da venda", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btconfirmardadosvendaActionPerformed

    private void rbdinheiroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbdinheiroItemStateChanged
        // TODO add your handling code here:
        if(rbdinheiro.isSelected()){
            Double subtotalcomdesconto=Double.parseDouble(txtsubtotal.getText());
            if(!txtdesconto.getText().isEmpty()){
                subtotalcomdesconto=subtotalcomdesconto*(100-Double.parseDouble(txtdesconto.getText()))/100;
            }
            cbnumparcelas.setModel(new DefaultComboBoxModel(new Object[]{"1x "+formatnumber.format(subtotalcomdesconto).replaceAll(",", ".")+" juros: 0%"}));
            txttaxajuros.setText("0");
            txttotal.setText(formatnumber.format(subtotalcomdesconto).replace(",", "."));
            txtvalorpago.setText("");
            txttroco.setText("");
            txtvalorpago.setEnabled(true);
            txtvalorpago.requestFocus();
            btefetuarvenda.setEnabled(false);
        }
    }//GEN-LAST:event_rbdinheiroItemStateChanged

    private void txtvalorpagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorpagoKeyReleased
        // TODO add your handling code here:
        if(!txtvalorpago.getText().isEmpty()){
            try{
                Double valorpago=Double.parseDouble(txtvalorpago.getText());
                if(valorpago>=Double.parseDouble(txttotal.getText())){
                    txttroco.setText(formatnumber.format(valorpago-Double.parseDouble(txttotal.getText())).replaceAll(",", "."));
                    btefetuarvenda.setEnabled(true);
                }
                else{
                    txttroco.setText("0.00");
                }
                System.out.println("aki");
            }
            catch(Exception e){
                txttroco.setText("0.00");
            }
        }
        else{
            txttroco.setText("0.00");
        }
    }//GEN-LAST:event_txtvalorpagoKeyReleased

    private void rbcreditoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbcreditoItemStateChanged
        // TODO add your handling code here:
        if(rbcredito.isSelected()){
            List<FormaPagamento> listfp=new FormaPagamento().listarParcelasJurosPorFormaPagamentoTipo(true, true);
            cbnumparcelas.removeAllItems();
            Double subtotalcomdesconto=Double.parseDouble(txtsubtotal.getText());
            Double taxadesconto=0.00;
            if(!txtdesconto.getText().isEmpty()){
                taxadesconto=Double.parseDouble(txtdesconto.getText());
            }
            for(FormaPagamento fp:listfp){
                cbnumparcelas.addItem(""+fp.getNumParcelas()+"x "+formatnumber.format(subtotalcomdesconto*((100+fp.getTaxaJuros()-taxadesconto))/100/fp.getNumParcelas()).replace(",", ".")+" juros: "+fp.getTaxaJuros()+"%");
            }
            txtvalorpago.setText(txttotal.getText());
            txttroco.setText("0.00");
            txtvalorpago.setEnabled(false);
            btefetuarvenda.setEnabled(true);
        }
        
    }//GEN-LAST:event_rbcreditoItemStateChanged

    private void rbdebitoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbdebitoItemStateChanged
        // TODO add your handling code here:
        if(rbdebito.isSelected()){
            List<FormaPagamento> listfp=new FormaPagamento().listarParcelasJurosPorFormaPagamentoTipo(true, false);
            cbnumparcelas.removeAllItems();
            Double subtotalcomdesconto=Double.parseDouble(txtsubtotal.getText());
            Double taxadesconto=0.00;
            if(!txtdesconto.getText().isEmpty()){
                taxadesconto=Double.parseDouble(txtdesconto.getText());
            }
            for(FormaPagamento fp:listfp){
                cbnumparcelas.addItem(""+fp.getNumParcelas()+"x "+formatnumber.format(subtotalcomdesconto*((100+fp.getTaxaJuros()-taxadesconto))/100/fp.getNumParcelas()).replace(",", ".")+" juros: "+fp.getTaxaJuros()+"%");
            }
            txtvalorpago.setText(txttotal.getText());
            txttroco.setText("0.00");
            txtvalorpago.setEnabled(false);
            btefetuarvenda.setEnabled(true);
        }
        
    }//GEN-LAST:event_rbdebitoItemStateChanged

    private void cbnumparcelasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbnumparcelasItemStateChanged
        // TODO add your handling code here:
        if(cbnumparcelas.getItemCount()>0){
            String valorcb=cbnumparcelas.getSelectedItem().toString();
            Double taxajuros=Double.parseDouble(valorcb.split(":")[1].split("%")[0].trim());
            txttaxajuros.setText(Double.toString(taxajuros));
            Double subtotal=Double.parseDouble(txtsubtotal.getText());
            Double taxadesconto=0.00;
            if(!txtdesconto.getText().isEmpty()){
                taxadesconto=Double.parseDouble(txtdesconto.getText());
            }
            txttotal.setText(formatnumber.format(subtotal*(100+taxajuros-taxadesconto)/100).replaceAll(",", "."));
        }
        
    }//GEN-LAST:event_cbnumparcelasItemStateChanged

    private void btaplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaplicarActionPerformed
        // TODO add your handling code here:
        if(!txtdesconto.getText().isEmpty()){
            txttotal.setText(formatnumber.format((100-Double.parseDouble(txtdesconto.getText()))*Double.parseDouble(txtsubtotal.getText())/100).replaceAll(",","."));
        }
        if(txttotal.getText().equals(txtsubtotal.getText())){
            txtdesconto.setText("0");
        }
        txtdesconto.setEnabled(false);
        btaplicar.setEnabled(false);
    }//GEN-LAST:event_btaplicarActionPerformed

    private void btefetuarvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btefetuarvendaActionPerformed
        // TODO add your handling code here:
        Venda v=pegarDadosCampos();
        if(v!=null){
            if(v.salvar()){
                JOptionPane.showMessageDialog(rootPane, "Venda efetuada com sucesso", "Operação efetuada", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Verifique se você está conectado servidor de banco de dados", "Operação não efetuada", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique se os campos foram preenchidos corretamente", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btefetuarvendaActionPerformed

    private void txtnomeprodutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeprodutoFocusLost
        // TODO add your handling code here:
        try {
            Produto p = (Produto) cbnomeproduto.getSelectedItem();
            Estoque estoque = new Estoque().listarEstoquePorProdutoId(p.getId()).get(0);
            txtcodproduto.setText(estoque.getCodBarra().toString());
            txtnomeproduto.setText(p.getNome());
            cbcategoria.setModel(new DefaultComboBoxModel(new Object[]{estoque.getProduto().getCategoriaProduto()}));
            txtvalorunitario.setText(formatnumber.format(estoque.getProduto().getValorUnitario()));
            txtqtdproduto.requestFocus();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_txtnomeprodutoFocusLost

    private void txtcodprodutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcodprodutoFocusLost
        // TODO add your handling code here:
        if (!txtcodproduto.getText().isEmpty()) {
            List<Estoque> lista = new Estoque().listarPorCodBarra(Long.parseLong(txtcodproduto.getText()));
            try {
                Estoque estoque = lista.get(0);
                cbcategoria.setModel(new DefaultComboBoxModel(new Object[]{estoque.getProduto().getCategoriaProduto()}));
                txtnomeproduto.setText(estoque.getProduto().getNome());
                cbnomeproduto.setModel(new DefaultComboBoxModel(new Object[]{estoque.getProduto()}));
                txtvalorunitario.requestFocus();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_txtcodprodutoFocusLost

    Venda pegarDadosCampos(){
        Venda v=new Venda();
        v.setId(null);
        v.setFuncionarioId(MenuPrincipal.funcionario);
        if(cbpesquisacliente.getItemCount()>0){
            v.setClienteId((Cliente)cbpesquisacliente.getSelectedItem());
        }
        else{
            v.setClienteId(null);
        }
        
        SimpleDateFormat formatador=new SimpleDateFormat("dd/MM/yyyy");
        try {
            v.setDataVenda(formatador.parse(formatador.format(new Date())));
        } catch (ParseException ex) {
            System.out.println("Data invalida");
        }
        Boolean cartao=!rbdinheiro.isSelected();
        Boolean tipo=false;
        if(cartao){
            tipo=rbcredito.isSelected();
        }
        Integer numparcelas=Integer.parseInt(cbnumparcelas.getSelectedItem().toString().split("x")[0]);
        v.setFormaPagamentoId(new FormaPagamento().listarPorTipoCartaoParcelas(cartao, tipo, numparcelas).get(0));
        v.setValorTotal(Double.parseDouble(txttotal.getText()));
        v.setValorJuros(Double.parseDouble(txtsubtotal.getText())*Double.parseDouble(txttaxajuros.getText())/100);
        v.setValorDesconto(Double.parseDouble(txtsubtotal.getText())*Double.parseDouble(txtdesconto.getText()));
        List<EstoqueVenda> listestoquevenda=new ArrayList();
        for(int i=0; i<tbproduto.getRowCount(); i++){
            EstoqueVenda estoquevenda=new EstoqueVenda();
            estoquevenda.setEstoque(new Estoque().listarPorCodBarra(Long.parseLong(tbproduto.getValueAt(i, 0).toString())).get(0));
            estoquevenda.setValorUnitario(Double.parseDouble(tbproduto.getValueAt(i, 2).toString()));
            estoquevenda.setQuantidade(Integer.parseInt(tbproduto.getValueAt(i, 3).toString()));
            estoquevenda.setVenda(v);
            listestoquevenda.add(estoquevenda);
        }
        v.setEstoqueVendaList(listestoquevenda);
        return v;
    }
    
    
    void modificarStatusCampos(Boolean b){
        txtpesquisacliente.setEnabled(!b);
        cbpesquisacliente.setEnabled(!b);
        txtcodproduto.setEnabled(!b);
        cbcategoria.setEnabled(!b);
        txtnomeproduto.setEnabled(!b);
        cbnomeproduto.setEnabled(!b);
        txtqtdproduto.setEnabled(!b);
        
        txtdesconto.setEnabled(b);
        rbcredito.setEnabled(b);
        rbdebito.setEnabled(b);
        rbdinheiro.setEnabled(b);
        cbnumparcelas.setEnabled(b);
        txtvalorpago.setEnabled(b);
        
        btaplicar.setEnabled(b);
        btconfirmardadosvenda.setEnabled(!b);
        btefetuarvenda.setEnabled(b);
    }
    
    void limparCampos(){
        txtpesquisacliente.setText("");
        cbpesquisacliente.removeAllItems();
        txtcodproduto.setText("");
        cbcategoria.removeAllItems();
        txtnomeproduto.setText("");
        cbnomeproduto.removeAllItems();
        txtvalorunitario.setText("");
        txtqtdproduto.setText("");
        ((DefaultTableModel)tbproduto.getModel()).setRowCount(0);
        txtsubtotal.setText("0.00");
        txtdesconto.setText("0");
        rbdinheiro.setSelected(true);
        cbnumparcelas.removeAllItems();
        cbnumparcelas.addItem("1x 0.00 juros: 0%");
        txttaxajuros.setText("0");
        txttotal.setText("0.00");
        txtvalorpago.setText("");
        txttroco.setText("");
        modificarStatusCampos(false);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaplicar;
    private javax.swing.JButton btconfirmardadosvenda;
    private javax.swing.JButton btefetuarvenda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbcategoria;
    private javax.swing.JComboBox cbnomeproduto;
    private javax.swing.JComboBox cbnumparcelas;
    private javax.swing.JComboBox cbpesquisacliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcategoria;
    private javax.swing.JLabel lbcodproduto;
    private javax.swing.JLabel lbdesconto;
    private javax.swing.JLabel lbformapag;
    private javax.swing.JLabel lbinfocliente;
    private javax.swing.JLabel lbinfopagamento;
    private javax.swing.JLabel lbinfoprodutos;
    private javax.swing.JLabel lbnomeproduto;
    private javax.swing.JLabel lbnumparcelas;
    private javax.swing.JLabel lbpesquisa;
    private javax.swing.JLabel lbqtdproduto;
    private javax.swing.JLabel lbsubtotal;
    private javax.swing.JLabel lbtaxajuros;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JLabel lbtroco;
    private javax.swing.JLabel lbvalorpago;
    private javax.swing.JLabel lbvalorunitario;
    private javax.swing.JLabel lbvenda;
    private javax.swing.JPanel panelproduto;
    private javax.swing.JRadioButton rbcredito;
    private javax.swing.JRadioButton rbdebito;
    private javax.swing.JRadioButton rbdinheiro;
    private javax.swing.JTable tbproduto;
    private javax.swing.JTextField txtcodproduto;
    private javax.swing.JTextField txtdesconto;
    private javax.swing.JTextField txtnomeproduto;
    private javax.swing.JTextField txtpesquisacliente;
    private javax.swing.JTextField txtqtdproduto;
    private javax.swing.JFormattedTextField txtsubtotal;
    private javax.swing.JTextField txttaxajuros;
    private javax.swing.JFormattedTextField txttotal;
    private javax.swing.JFormattedTextField txttroco;
    private javax.swing.JFormattedTextField txtvalorpago;
    private javax.swing.JTextField txtvalorunitario;
    // End of variables declaration//GEN-END:variables
}
